### ISSUE TITLE
Wrangle Wine Data

### ISSUE THREAD

**Issue by dborncamp** [dborncamp/ScienceSaturday#1]
The 30 minutes or so I spent trying to wrangle the wine data into a useable forum did not go so well. Wrangle that data into submission and make nice csv files that can be read into a dataframe of some sort to be properly analyzed.

**Comment by rjavila** [comment]
I think has been taken care of by pull request #14 . There are some wine files in the data directory, but I don't know if they are what you want.

**Comment by Rplesha** [comment]
Pull request #18 should address this issue
