### ISSUE TITLE
Re-organize directories

### ISSUE THREAD

**Issue by rjavila** [dborncamp/ScienceSaturday#13]
Sup,

I have some code I wrote using bokeh to visualize some of results from Science Saturday 2&3. We might have to do some re-arranging of the directory structure to get things going. I suggest making a directory for each SS. Thoughts?

**Comment by dborncamp** [comment]
Seems like a good idea. Open a PR for it!

**Comment by rjavila** [comment]
I mentioned that I wrote some Bokeh code, but in the PR I submitted I no longer use that because it is much easier to do thing using Ipywidgets.

**Comment by dborncamp** [comment]
Should there be a `scienceSaturday01` directory?

**Comment by rjavila** [comment]
There should be, I just haven't gotten around to it. We're also doing a SS4 this weekend.

**Comment by dborncamp** [comment]
closed by #14
