### ISSUE TITLE
Major re-write of README

### ISSUE THREAD

**Issue by rjavila** [dborncamp/ScienceSaturday#28]
Now that we have a website, I don't know if we need to put together "a paper" for the arxiv. I'm proposing we eliminate that stuff from the README file. Unless anyone has any objection I'm gonna take a stab at a new README.  @dborncamp @Rplesha

**Comment by dborncamp** [comment]
That sounds good. A paper isn't as useful as a website.

**Comment by rjavila** [comment]
Should we get rid of the `tex` directory in the repo?
Also, do we still all the section `analysis environment`? I think we're doing things differently nowadays.

**Comment by rjavila** [comment]
I have a new version of the README ready that I will push in a bit. I'll make a new issue to deal with cleaning up the repo.

**Comment by Rplesha** [comment]
I think we should branch off the latest version of the repo as “archival-documentation” or something before we remove it. That way we can point to it and the work isn’t lost for forever, but it can then be removed from main for cleanup.
